name: tpm_absensi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  provider: ^6.1.5
  geolocator: ^13.0.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
